function [] = SimplexGUI()
% Disclaimer:
% I have edited the original file GUI_6 to obtain this GUI
% The GUI_6 file I obtained is from:
% http://www.mathworks.com/matlabcentral/fileexchange/24861-41-complete-gui-examples
% Author:  Matt Fig
% Date:  7/15/2009
% Editted by Huda Nassar on April 28, 2015 for the CS 520 Project of SP15



S.fh = figure('units','pixels',...
    'position',[400 400 120 170],...
    'menubar','none',...
    'name','Simplex',...
    'numbertitle','off',...
    'resize','off');
S.pb = uicontrol('style','push',...
    'unit','pix',...
    'position',[10 10 100 20],...
    'string','Apply Simplex',...
    'tooltip','Push to find out which radio button is selected');

S.rd(1) = uicontrol('style','rad',...
    'unit','pix',...
    'position',[10 130 100 20],...
    'string','  lpi_itest6.mat');
S.rd(2) = uicontrol('style','rad',...
    'unit','pix',...
    'position',[10 100 100 20],...
    'string','  lpi_chemcom');
S.rd(3) = uicontrol('style','rad',...
    'unit','pix',...
    'position',[10 70 100 20],...
    'string','  lp_agg3.m');
S.rd(4) = uicontrol('style','rad',...
    'unit','pix',...
    'position',[10 40 100 20],...
    'string','  lp_80bau3b.m');


set(S.pb,'callback',{@pb_call2,S});

function [] = pb_call2(varargin)

% Callback for pushbutton.
S = varargin{3};  % Get structure.
R = [get(S.rd(1),'val'), get(S.rd(2),'val'), get(S.rd(3),'val'),get(S.rd(4),'val')];  % Get state of radios.
includeFiles = zeros(4,1);
for i = 1:4
    if R(i) == 1
        includeFiles(i) = 1;
    end
end
simplexMain;
create_msgbox(input_message);